### ISSUE TITLE
In the Person class

### ISSUE THREAD

**Issue by BashirKad** [MariaMa-GitHub/group_project#3]
@MariaMa-GitHub If we want to limit the amount of items a single Person can check out, why make it an ArrayList? I think it would just be easier for you to make it into an array with a fixed limit, but if you have something else planned that's fine. Just want to know for the method I'm writing rn

**Comment by MariaMa-GitHub** [comment]
1. It’s easier to work with (methods like add and remove/pop if I am not
mistaken). With an array if you remove an item than the slot at that index
is going to be empty and if you want to add another one you would have to
check whether or not there is an empty space and if yes where is the first
one
2. We are already using ArrayLists for pretty much the entire project (like
ur instance variables) so it’s simpler if I keep on using that.

**Comment by BashirKad** [comment]
Alright, sounds good. Just wanted to make sure we're all on the same page

**Comment by MariaMa-GitHub** [comment]
👌
