### ISSUE TITLE
Google Meet

### ISSUE THREAD

**Issue by MariaMa-GitHub** [MariaMa-GitHub/group_project#32]
@actualbobbernauts @bobyangg @BashirKad Do you want to meet in a separate Google Meet or no?

**Comment by BashirKad** [comment]
I think we're good for now? You guys have (hopefully) everything you wanted to get done finished (maybe like 1 or 2 things) so aslong as you guys sort out all the merging, I'll just have my GUI thing left which is almost done (I'll update in this thread if I need help/anything else) and I'll try to merge it (making sure not to mess up anything you guys had)

**Comment by bobyangg** [comment]
Are all the files on the repo the finalized ones?

**Comment by bobyangg** [comment]
Also do you guys know if we need to all hand in the files or just one us

**Comment by MariaMa-GitHub** [comment]
We can just hand in the github link Ig

**Comment by MariaMa-GitHub** [comment]
And we can all hand it in just in case

**Comment by MariaMa-GitHub** [comment]
@actualbobbernauts @bobyangg @BashirKad Btw, just to remind you all, the Google Sheets is not yet completed so if you want to add/change something in it (especially for your own class) then don't forget to do it.

**Comment by BashirKad** [comment]
Is she correcting anything on the sheets or is it just for us to use? 
Also while I'm at it, just to update for the GUI class it's pretty close to done, just need to do all the if statement stuff for getting a book, but returning books and everything "before that" (if that makes any sense) all works

**Comment by MariaMa-GitHub** [comment]
kk

PS: idk she didn't really say

**Comment by BashirKad** [comment]
Alright, everything is 100% done for the code and I'm not going to make any more edits, who wants to submit it?

**Comment by MariaMa-GitHub** [comment]
I guess we can all submit it. Just in case. It doesn’t hurt.

**Comment by BashirKad** [comment]
how do we link a repo then?

**Comment by MariaMa-GitHub** [comment]
sure

**Comment by actualbobbernauts** [comment]
uh this is gonna sound dumb but how do i link the repository lol

**Comment by BashirKad** [comment]
I had to google it too, just go to the main repo page and click the green Code button and there should be URL there

**Comment by actualbobbernauts** [comment]
ok thanks bro

**Comment by BashirKad** [comment]
wait can someone remind me, did she say it was okay if we handed in the report late?

**Comment by MariaMa-GitHub** [comment]
Nah I don't think so. I think it's due tonight. Ugh I am also working on it.

**Comment by actualbobbernauts** [comment]
I don't think she'll be that mad? Safer to hand it in tonight tho. And yea I speedran 1000 words in 30 mins

**Comment by MariaMa-GitHub** [comment]
@BashirKad If you can respond, is that normal:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/78451694/149609153-44a40c51-0b55-4f0a-b77a-dc361c36745a.png">

**Comment by BashirKad** [comment]
No it shouldn't? I just tested it on mine and I ran into no error, what steps did you before getting there?

**Comment by MariaMa-GitHub** [comment]
ohhhhhhhh I tried again and it works now. weeeeeeeeeeeeird. sorry for that
